image: gitlab-registry.cern.ch/ci-tools/ci-worker:cc7

build:
  stage: build
  tags:
    - docker
    - cvmfs
  script:
    - pwd
    - ls -l
    - mkdir Rivet
    - find -maxdepth 1 -mindepth 1 -not -name Rivet -exec mv {} Rivet/ \;
    - SCRAM_ARCH=slc7_amd64_gcc820 /cvmfs/cms.cern.ch/common/scramv1 project CMSSW CMSSW_11_0_1
    - mv Rivet CMSSW_11_0_1/src/
    - cd CMSSW_11_0_1/src
    - eval `/cvmfs/cms.cern.ch/common/scramv1 runtime -sh`
    - /cvmfs/cms.cern.ch/common/scram b -j 8
  artifacts:
    expire_in: 1 day
    paths:
      - CMSSW_11_0_1

list-analyses:
  stage: test
  tags:
    - docker
    - cvmfs
  script:
    - cd CMSSW_11_0_1/src
    - eval `/cvmfs/cms.cern.ch/common/scramv1 runtime -sh`
    - source Rivet/rivetSetup.sh
    - rivet --list-analyses | grep MC_GENERIC
    - rivet --list-analyses

check-tabs:
  stage: test
  tags:
    - docker
    - cvmfs
  script:
    - pwd
    - ls -l
    - cd CMSSW_11_0_1/src/Rivet
    - ls -l
    - echo '! grep -rnP "\t" * | grep "\.cc"' | bash
